[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
PYTHONUNBUFFERED = "1"
UV_SYSTEM_PYTHON = "1"

# Application Configuration
APP_ENV = { default = "production" }
DEBUG = { default = "False" }
AGENT_RECURSION_LIMIT = { default = "10" }
MAX_SEARCH_RESULTS = { default = "2" }
MAX_STEP_NUM = { default = "2" }
STREAM_TIMEOUT_SECONDS = { default = "1800" }

# Search API Configuration - Tavily for production
SEARCH_API = { default = "tavily" }
TAVILY_API_KEY = { default = "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" }

# OpenRouter LLM Configuration
OPENROUTER_API_KEY = { default = "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" }

# Basic Model Configuration
BASIC_MODEL__BASE_URL = { default = "https://openrouter.ai/api/v1" }
BASIC_MODEL__MODEL = { default = "openrouter/google/gemini-2.5-flash-preview-05-20" }
BASIC_MODEL__API_KEY = { default = "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" }

# Reasoning Model Configuration
REASONING_MODEL__BASE_URL = { default = "https://openrouter.ai/api/v1" }
REASONING_MODEL__MODEL = { default = "openrouter/google/gemini-2.5-flash-preview-05-20" }
REASONING_MODEL__API_KEY = { default = "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" }

# Vision Model Configuration
VISION_MODEL__BASE_URL = { default = "https://openrouter.ai/api/v1" }
VISION_MODEL__MODEL = { default = "openrouter/google/gemini-2.5-flash-preview-05-20" }
VISION_MODEL__API_KEY = { default = "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" }
